### ISSUE TITLE
Updating results for ogbl-citation2

### ISSUE THREAD

**Issue by weihua916** [facebookresearch/SEAL_OGB#10]
We have updated the `ogbl-citation` dataset to `ogbl-citation2` (available in version ogb>=1.2.4). We appreciate it if you could re-evaluate your model on the new dataset and make the leaderboard submission. Sorry for the extra work.

Thanks,
Weihua --- OGB Team

**Comment by muhanzhang** [comment]
Hi! I have got the new results. I plan to submit them together with the updated arxiv paper this week. Thanks!

**Comment by weihua916** [comment]
That makes sense. Thank you!

**Comment by weihua916** [comment]
Thanks for the resubmission. The leaderboard has been updated. Please feel free to close the issue once you have updated the README. Thanks!

**Comment by muhanzhang** [comment]
@weihua916 Hi Weihua, thanks for updating the leaderboard! Can you also help change the other SEAL submissions' paper to "https://arxiv.org/pdf/2010.16103.pdf"? During the last submission, many reviewers got confused about which is the first paper containing these OGB leaderboard results. 

Also, I have submitted the results for two simple link prediction heuristics, Common Neighbor and Adamic Adar. Although they are very simple (no training involved), they surprisingly can outperform many GNN-based methods. I think they are good baselines for sanity checking GNN's link prediction power.

**Comment by weihua916** [comment]
Thank you Muhan! Yes, I have modified the link of SEAL submissions as suggested.

The simple baseline submissions are indeed very informative and great contributions to OGB. Thank you for that.

**Comment by muhanzhang** [comment]
@weihua916 Hi Weihua! I just found the citation2 results I submitted had the wrong std digits. The test std should be 0.0031, and the validation std should be 0.0032. Sorry for the trouble!

**Comment by weihua916** [comment]
No worries. Corrected. Could you also update the README.md? Thanks!

**Comment by muhanzhang** [comment]
Just done! Thanks!
