### ISSUE TITLE
Problems using custom dataset

### ISSUE THREAD

**Issue by jqmcginnis** [facebookresearch/SEAL_OGB#11]
Hi!

Thank you very much for providing the code for your impressive paper and the possibility of testing SEAL for custom datasets.
At the moment, I would like to use the dynamic SEAL variant for testing my large custom dataset. 

Running: 
`seal_link_pred.py --dataset MyGraph --num_hops 1 --dynamic_train --dynamic_val --dynamic_test`

fails with the out of memory error:

`../anaconda3/envs/pytorch_geometric/lib/python3.8/site-packages/torch_geometric/utils/train_test_split_edges.py", line 50, in train_test_split_edges
    neg_adj_mask = torch.ones(num_nodes, num_nodes, dtype=torch.uint8)
RuntimeError: [enforce fail at CPUAllocator.cpp:65] . DefaultCPUAllocator: can't allocate memory`

When SEAL automatically tries to split the edges, my script crashes:
`path = osp.join('dataset', args.dataset)`
 `dataset = Planetoid(path, args.dataset) # replaced by my dataset`
 `split_edge = do_edge_split(dataset)`
 `data = dataset[0]`
 `data.edge_index = split_edge['train']['edge'].t()`

What would be the best way to mitigate this? As we need split_edge later, I wanted to ask for the most convinient way of handling this?

Thank you!

**Comment by muhanzhang** [comment]
Hi @jqmcginnis ! Thanks for your interest in the work. From the message, it seems the `train_test_split_edges.py` causes the OOM. In fact, this function is implemented only for small datasets because it requires to create a dense N * N matrix as neg_adj_mask which is not scalable. I suggest replacing this function with a custom negative sampling function. For example, you can simply randomly sample non-existing links (node pairs) as your negative data.

**Comment by jqmcginnis** [comment]
Thank you @muhanzhang that was very helpful, I will definitely try that! Thank you for your time!

**Comment by SYLin117** [comment]
Hi @jqmcginnis I'm facing the same problem here, did you find any solution? Really need some help here 😭.

**Comment by jqmcginnis** [comment]
Hi @SYLin117, I have not implemented a more memory friendly splitting function (yet), as we decided to improve our dataset first and I conducted tests on smaller (sub-)graphs. Not sure, if this is an option for you. I would also recommend the OGB paper on splitting data in general, random splitting might not be the best strategy for your dataset. However, if you need to randomly split your complete dataset and want to utilize a similar function, you could utilize numpy's memmap functionality which provides the possibility of working on huge arrays on your disk (and not in RAM). Does this help?

**Comment by muhanzhang** [comment]
@SYLin117 I added a [fast_split](https://github.com/facebookresearch/SEAL_OGB/commit/34343e8ab96513339260d63db8f198e08ef78300) function for splitting large custom datasets. Please let me know whether it solves your problem.

**Comment by SYLin117** [comment]
@jqmcginnis thanks for the reply, I would definitely try.
@muhanzhang It works fine! Thanks a lot!
