### ISSUE TITLE
Batch in the graph mean ?

### ISSUE THREAD

**Issue by NguyenTruongThanh-74** [facebookresearch/SEAL_OGB#19]
I see you set batch_size=32 but input is only 1 subgraph, and label output is 32. I don't understand that.
And When I using drnl to label why in the graph have node label 0.

**Comment by muhanzhang** [comment]
1. When you set batch_size = 32, the input should be 32 subgraphs. However, they are compressed into one large graph (with disconnected componenets) for batch processing. So you may see only 1 subgraph.

2. Node label 0 is for marking those nodes with infinite distance to one of the two target nodes.

**Comment by NguyenTruongThanh-74** [comment]
Excuse me, the Model can't run multiple edges predict in one graph, your solution is to train many times with z_score different right?

**Comment by muhanzhang** [comment]
That's right. For every new link to predict, you need to relabel the subgraph extracted for this link and apply the GNN. However, the training only happens once over all the training links.
