### ISSUE TITLE
Multi-relational link prediction in a heterogeneous graph

### ISSUE THREAD

**Issue by sophiakrix** [facebookresearch/SEAL_OGB#22]
Hi there!

Amazing work with the SEAL approach! I was wondering how could could apply the scoring to multi-relational link prediction task. Since you mentioned in the paper that SEAL is not restricted to homogeneous graphs, I was wondering how the implementation has to be adapted to calculate the score for different edge types. Could you possibly show how to do that?

Best,

Sophia

**Comment by muhanzhang** [comment]
Hi Sophia,

Thanks! SEAL has already been applied to recommender systems (where relations are of multilple types corresponding to different ratings), see https://github.com/muhanzhang/IGMC. Basically, you need to change GCN to R-GCN to handle edge types, and change the loss to multi-class classification or regression loss.

**Comment by sophiakrix** [comment]
Hi @muhanzhang,

Thanks a lot for the response! I will try this out. Would you say that I could rather use the IGMC code instead of changing the SEAL code?  What would be the difference?

**Comment by muhanzhang** [comment]
@sophiakrix The IGMC code reads recommender system datasets such as Movielens, Flixster, etc (which are bipartite graphs). I would still recommend to adapt this SEAL_OGB repo to your task, because it reads general graphs.

**Comment by sophiakrix** [comment]
Thanks for the reply!

**Comment by sophiakrix** [comment]
Thanks for the suggestion!
