### ISSUE TITLE
Issues with heuristic methods, i.e., CN and AA

### ISSUE THREAD

**Issue by CongWeilin** [facebookresearch/SEAL_OGB#25]
Hi, I found the testing performance of the heuristic method I got is significantly different from the one reported on the open graph benchmark. For example:

Running the following command gives me **Hits@50 Valid 63.49, test 53.00**. 
```
python seal_link_pred.py --use_heuristic AA --dataset ogbl-collab
```

Running the following command gives me **Hits@50 Valid 60.36, test 50.06**. 
```
python seal_link_pred.py --use_heuristic CN --dataset ogbl-collab
```

The result is very different from the open graph benchmark's reported one.

I went through the code on GitHub, but couldn't figure out why.

**Comment by muhanzhang** [comment]
Hi, you need to append "--use_valedges_as_input" for ogbg-collab. See this [issue](https://github.com/snap-stanford/ogb/issues/84).

**Comment by CongWeilin** [comment]
The issue is resolved. Thanks!
