### ISSUE TITLE
Requesting command line arguments needed for reproducing OGBL leaderboard results

### ISSUE THREAD

**Issue by venomouscyanide** [facebookresearch/SEAL_OGB#27]
Hi Dr. Zhang,

I was wondering if the exact commands that can be used to reproduce the [OGBL leaderboard](https://ogb.stanford.edu/docs/leader_linkprop/) SEAL results were available somewhere? 
I was running some experiments trying to reproduce the results showcased on the leaderboards for the undirected homogeneous datasets [ogbl-ddi](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-ddi), [ogbl-collab](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-collab) and [ogbl-ppa](https://ogb.stanford.edu/docs/leader_linkprop/#ogbl-ppa) using this repo.

Thanks a lot in advance!

**Comment by muhanzhang** [comment]
Hi! The exact commands are the ones included in the repository's README.

**Comment by venomouscyanide** [comment]
@muhanzhang Thanks a lot! I'll try using it.
Closing the issue.

**Comment by venomouscyanide** [comment]
Closing as resolved in comments.
