### ISSUE TITLE
Question regarding `use_edge_weight` parameter for training `ogbl-ddi` and `ogbl-ppa`

### ISSUE THREAD

**Issue by venomouscyanide** [facebookresearch/SEAL_OGB#28]
Hi Dr. Zhang,

I was trying to recreate experimental results for `ogbl-ddi` and `ogbl-ppa`. However, I saw the argument `use_edge_weight` being used. I might be wrong here, but, aren't `ogbl-ddi`  and `ogbl-ppa` unweighted datasets?

Is this done to use a vector of ones as edge weight during training? If so, I am curious to know why it's needed.

Thanks,
Paul

**Comment by muhanzhang** [comment]
Hi Paul! Yes, your understanding is correct. Even some datasets do not contain edge weights, GNNs can still use all-one edge weights in their forward computations. This is automatically handled by the GCNConv implementation. Thus, for ddi and ppa, I think you can safely delete `--use_edge_weight` and get the same performance.

**Comment by venomouscyanide** [comment]
Thank you for the reply. I believe edge weights are used in the forward propagation in DGCCN and GCN so it makes perfect sense.
