### ISSUE TITLE
A clarification on SEAL’s underlying GNN engine

### ISSUE THREAD

**Issue by venomouscyanide** [facebookresearch/SEAL_OGB#29]
Hi Dr. Zhang,   

I had the pleasure of reading the [labeling trick paper](https://proceedings.neurips.cc/paper/2021/file/4be49c79f233b4f4070794825c323733-Paper.pdf). I was quite curious upon reading it as to what can be regarded as the SEAL model. Can we call GCN + DRNL labelled subgraphs + SortPooling aggregation as SEAL?  
Or can we only call the model as SEAL if it uses DGCNN as the underlying backbone, thus making the model DGCNN + DRNL labelled subgraphs + SortPooling aggregation as last step?
  I guess I am just confused if GCN + DRNL becomes SEAL only if you use SortPooling at the end. Sorry if the question is a bit difficult to understand. I can clarify further as needed.

  - Paul

**Comment by muhanzhang** [comment]
Hi Paul! Thanks for the question. Firstly, I would like to clarify that DGCNN is indeed GCN + SortPooling.

 In general, I would classify any model using a GNN + DRNL labeling trick as SEAL. Although the original SEAL framework adopts the DGCNN (i.e., GCN + SortPooling) as the GNN, it essentially does not restrict the GNN to be specifically DGCNN but allows using any GNN with a pooling layer. So even a GCN + sum-pooling + DRNL can still be called a SEAL model.

**Comment by venomouscyanide** [comment]
Hi Dr. Zhang,

Thank you for the detailed explanations. Your replies help a lot.

I had a follow up question. Referring to the image attached(Taken from [labelling tricks](https://proceedings.neurips.cc/paper/2021/file/4be49c79f233b4f4070794825c323733-Paper.pdf) table 1), won't `GCN+DRNL` become `SEAL`?
 
![table1.png](https://user-images.githubusercontent.com/14299839/168454536-2d9681cf-2f89-4d5b-bdd5-9bbd66a6e31d.png)

-Paul

**Comment by muhanzhang** [comment]
Right. Depending on the context, I specifically use SEAL there to denote the exact SEAL (DGCNN + DRNL), in order to compare with GCN + DRNL. Apart from that, SEAL (in general) uses a subgraph-level pooling layer to pool all node representations in the subgraph as the link representation, while GCN + DRNL only pools the source and target nodes' representations.

**Comment by venomouscyanide** [comment]
That makes sense. Thank you for the clarification.
So I am guessing in this context(and from what I have seen in the code), `GCN + DRNL` uses centre pooling. However, if I make it such that it is `GCN + DRNL + Subgraph Pooling(eg; sum pooling/max pooling/sort pooling)`, it becomes `SEAL`?

**Comment by muhanzhang** [comment]
Yes, I would classify `GCN + DRNL + Subgraph Pooling` as a SEAL method.

**Comment by venomouscyanide** [comment]
Thank you so much for the detailed clarifications.

I am closing the issue as Dr. Zhang has explained the query in detail.
