### ISSUE TITLE
Question regarding output

### ISSUE THREAD

**Issue by vymao** [facebookresearch/SEAL_OGB#3]
Hi, 

I had another question about the output of SEAL_OGB. How do you restrict the output probability to be within 0 to 1? I see a tanh nonlinearity but I also see other layers afterwards without range restrictions, which seems to me that the predicted output could be negative or greater than 1.

**Comment by muhanzhang** [comment]
Hi! Link prediction is mainly a ranking problem (the metrics used are AUC, MRR, Hits@K, etc.). Thus, we can directly use the output scores (-inf to inf) to rank them without transforming them to probabilities. But outputing probabilities can be easily done by appending a sigmoid layer after the scores.

**Comment by vymao** [comment]
I see, thank you. I also noticed that you remove the source/dest edge in training. Would it still be valid if you instead set the source/dest edge to some predetermined value (for both positive and negative links)? That way, it seems there is still no information to be gained by the source/dest edge either.

**Comment by muhanzhang** [comment]
Yes, you can. You can even add an edge between source and destination nodes for all train/val/test links. As long as the model doesn't know the link existence information easily by checking the source/destination edge difference between pos/neg links, you are fine.

**Comment by vymao** [comment]
Hi, another quick question. I noticed you use negative sampling to generate negative edges. However, by default this seems to generate directed edges. Do you add in the reverse edge somewhere?

**Comment by muhanzhang** [comment]
No, but this is ok. For link (a, b) and its reverse (b, a), we don't need to sample it twice. The given positive edges are not necessarily undirected either.
