### ISSUE TITLE
Query regarding `--use_valedges_as_input`

### ISSUE THREAD

**Issue by venomouscyanide** [facebookresearch/SEAL_OGB#35]
Hi Dr. Zhang,

Hope you are doing good.

I had a query regarding the use of validation edges as input, which is useful in the `ogbl-collab` dataset as per the OGB rules. I noticed that when the flag `--use_valedges_as_input` is True, we have the following code snippet:

```
if args.use_valedges_as_input:
    val_edge_index = split_edge['valid']['edge'].t()
    if not directed:
        val_edge_index = to_undirected(val_edge_index)
    data.edge_index = torch.cat([data.edge_index, val_edge_index], dim=-1)
    val_edge_weight = torch.ones([val_edge_index.size(1), 1], dtype=int)
    data.edge_weight = torch.cat([data.edge_weight, val_edge_weight], 0)
```

But, since after hypertuning, we are allowed to use val_edges in training, can't we also update the `split_edge` as:
```
split_edge['train']['edge'] = torch.cat([data.edge_index, val_edge_index], dim=-1)
```
I was wondering if SEAL would benefit from this change/if this change makes sense. Any input is greatly appreciated!

Warm Regards,
Paul

**Comment by muhanzhang** [comment]
Hi Paul! Adding validation edges to the training set is totally feasible and might increase the performance. The reason I didn't add them was because I anyway sampled only a small portion of edges from the training set. Hope that helps!

**Comment by venomouscyanide** [comment]
Hi Dr. Zhang,

Makes sense! Thank you so much for the quick response. 

Marking this issue as resolved.
