### ISSUE TITLE
Regarding SEAL's performance on Cora, Citeseer and Pubmed

### ISSUE THREAD

**Issue by Barcavin** [facebookresearch/SEAL_OGB#36]
Hi Prof.Zhang,

I am trying to reproduce the performance of SEAL on Cora Citeseer and Pubmed. However, it seems that SEAL does not really perform well on these datasets, and it is even worse than a GNN encoder with Hadamard Product as a decoder. Given that SEAL is theoretically more powerful than a pure GNN and shows competitive results on other graph datasets like OGB, it does not make sense to me that it degenerates on these 3 common benchmarks.

I wonder if you had a chance to look over the SEAL's results on these 3 datasets and if you have some insights about its relative failure on them. I am assuming a more thorough hyperparameter tuning might be helpful but unfortunately, I didn't find the correct recipe to recover its full potential.

| Cora 	| Hits@20      	| Hits@50      	| AUC          	|
|------	|--------------	|--------------	|--------------	|
| GCN  	| 52.80 ± 1.50 	| 65.34 ± 2.08 	| 91.74 ± 0.65 	|
| SEAL 	| 44.45 ± 3.58 	| 58.15 ± 2.66 	| 86.13 ± 1.39 	|

| Citeseer 	| Hits@20      	| Hits@50      	| AUC          	|
|----------	|--------------	|--------------	|--------------	|
| GCN      	| 55.55 ± 2.38 	| 64.09 ± 3.34 	| 90.06 ± 1.06 	|
| SEAL     	| 45.46 ± 1.90 	| 54.53 ± 0.91 	| 82.72 ± 0.81 	|

| Pubmed 	| Hits@20      	| Hits@50      	| AUC          	|
|--------	|--------------	|--------------	|--------------	|
| GCN    	| 43.97 ± 2.00 	| 52.76 ± 1.00 	| 91.20 ± 0.50 	|
| SEAL   	| 39.89 ± 4.80 	| 48.65 ± 3.65 	| 96.08 ± 0.28 	|

The results above are 10%/20% split for val and test and average for 10 runs.

Thanks,

**Comment by Barcavin** [comment]
Thanks for your reply.

I ran the code with the official code in this repo. I might miss something but I didn't find the reported results in README. Actually, I didn't find the results for Planetoid on SEAL paper or Node Labelling paper. There are definitely reported results from other papers citing SEAL. But I do wonder if there are reported results for SEAL on Planetoid not just as baselines to compete with but to promote its strength.

> These datasets do not rely on structural features (such as common neighbor) that much like OGB. These datasets do not rely on structural features (such as common neighbor) that much like OGB.

I think SEAL is still more capable than GAE-like model. SEAL utilizes a GCN as an encoder to aggregate node attributes, which is the same as GAE. thus, it should be able to take advantage of the node features and be at least as good as these node-wise models. 

The only reason I can come up with for such a degenerate is that SEAL uses fixed negative sampling for each epoch due to the computation overhead of DRNL calculation, why GAE can sample more negative edges. I am not sure if there are other factors impairing its performance.

**Comment by muhanzhang** [comment]
Ok. I thought I put results in README... Anyhow, I meant I remember just running the provided commands should yield much better results than you reported. At least for Cora, I remember SEAL can easily reach 90+ AUC. Check another our paper: https://arxiv.org/pdf/2206.09567.pdf or the NBFNet paper: https://arxiv.org/pdf/2106.06935.pdf

**Comment by Barcavin** [comment]
Oh I think I ran the experiments with 10/20 split for val and test while the official code is 5/10 split. That's why it made a difference
