### ISSUE TITLE
Suitability for bipartite link prediction?

### ISSUE THREAD

**Issue by deklanw** [facebookresearch/SEAL_OGB#4]
Since this method is performing so well in unipartite prediction I'm wondering how it works for the bipartite case. Are there any possible modifications that need to be made in the bipartite setting?

OGB doesn't yet have any bipartite link prediction tasks, but it will: https://groups.google.com/g/open-graph-benchmark/c/Pd76nZri7tI

**Comment by muhanzhang** [comment]
Hi! There is a bipartite version of SEAL named IGMC: https://github.com/muhanzhang/IGMC. It works well for several matrix completion benchmarks. I will test it when OGB release bipartite graphs.

**Comment by deklanw** [comment]
Oh, thanks! I have a question about it but I'll open that there
