### ISSUE TITLE
SEAL vs 2-SEAL-RNN

### ISSUE THREAD

**Issue by seekingdeep** [facebookresearch/SEAL_OGB#7]
Hi there,
a more recent implementation of SEAL which is called 2-SEAL-RNN shows promising improvements and accuracy.
How is SEAL compared to 2-SEAL-RNN
https://arxiv.org/abs/2001.08427

**Comment by muhanzhang** [comment]
Hi! Thanks for suggesting the paper. 2-SEAL-RNN needs the inherent graph to be dynamic (each node has a time series), so that the RNN can model the dynamics of nodes. Thus, it does not suit the OGB datasets. The other introduced modifications can also be useful depending on datasets and problems.

**Comment by seekingdeep** [comment]
thanks
